ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ORDER_RENTER_CONFIRMED_RECEIVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'EARLY_RETURN_REQUESTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'EARLY_RETURN_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'EARLY_RETURN_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'EARLY_RETURN_RECEIVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ORDER_COMPLETED';
